/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { core } from '@balena/jellyfish-types';

interface ImageSourceData {
	data: {
		should_trigger: boolean;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface ImageSourceContractDefinition
	extends Omit<core.ContractDefinition, 'data'>,
		ImageSourceData {}

export interface ImageSourceContract
	extends Omit<core.Contract, 'data'>,
		ImageSourceData {}
