/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { core } from '@balena/jellyfish-types';

interface LoopData {
	[k: string]: unknown;
}

export interface LoopContractDefinition
	extends Omit<core.ContractDefinition, 'data'>,
		LoopData {}

export interface LoopContract extends Omit<core.Contract, 'data'>, LoopData {}
