/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { core } from '@balena/jellyfish-types';

interface ServiceData {
	[k: string]: unknown;
}

export interface ServiceContractDefinition
	extends Omit<core.ContractDefinition, 'data'>,
		ServiceData {}

export interface ServiceContract
	extends Omit<core.Contract, 'data'>,
		ServiceData {}
