/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { core } from '@balena/jellyfish-types';

interface TaskData {
	[k: string]: unknown;
}

export interface TaskContractDefinition
	extends Omit<core.ContractDefinition, 'data'>,
		TaskData {}

export interface TaskContract extends Omit<core.Contract, 'data'>, TaskData {}
