/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import { core } from '@balena/jellyfish-types';

interface TransformerWorkerData {
	data: {
		uuid: string;
		endpoint?: string;
		token?: string;
		transformers?: {
			id?: string;
			ref?: string;
			count?: string;
			[k: string]: unknown;
		}[];
		os?: string;
		architecture?: string;
		cpu_load?: number;
		ram?: {
			available?: number;
			total_mb?: number;
			[k: string]: unknown;
		};
		storage?: {
			available?: number;
			total_mb?: number;
			[k: string]: unknown;
		};
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface TransformerWorkerContractDefinition
	extends Omit<core.ContractDefinition, 'data'>,
		TransformerWorkerData {}

export interface TransformerWorkerContract
	extends Omit<core.Contract, 'data'>,
		TransformerWorkerData {}
